name: marsa_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  font_awesome_flutter: ^10.12.0
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# بداية قسم فلاتر، انتبه للمسافات هنا بدقة
flutter:
  uses-material-design: true

  # 1. قسم الصور (assets)
  # يجب أن يكون بمسافة بادئة (2 مسافة) تحت flutter
  assets:
    - assets/                  # للملفات الموجودة مباشرة داخل assets
    - assets/apartmentsImages/
    - assets/background/
    - assets/marsa/

  # 2. قسم الخطوط (fonts)
  # يجب أن يكون بمسافة بادئة (2 مسافة) تحت flutter
  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Regular.ttf